
INSERT INTO `items` (`id`, `name`, `house`, `tier`, `image`, `houseImage`)
VALUES
	(2,'Tywin Lannister','Lannister',3,'https://i.imgur.com/0prGvNm.png','https://vignette.wikia.nocookie.net/gameofthrones/images/8/8a/House-Lannister-Main-Shield.PNG/revision/latest?cb=20170101095357'),
	(3,'Podrick Payne','Payne',1,'https://i.imgur.com/7K5d8xi.png','https://i.imgur.com/xvSU8iY.png'),
	(4,'Cersei Lannister','Lannister',3,'https://i.imgur.com/TTy0VC9.png','https://vignette.wikia.nocookie.net/gameofthrones/images/3/38/House_Lannister.jpg/revision/latest?cb=20110409110354'),
	(5,'Margaery Tyrell','Tyrell',2,'https://i.imgur.com/LGsGQ4m.png','https://vignette.wikia.nocookie.net/gameofthrones/images/c/cf/House-Tyrell-Main-Shield.PNG/revision/latest?cb=20170108163035'),
	(6,'Khal Drogo','Other',1,'https://i.imgur.com/hMOMmCD.png',''),
	(7,'Robb Stark','Stark',2,'https://i.imgur.com/gYwdGFW.png',''),
	(8,'Theon Greyjoy','Tyrell',3,'https://i.imgur.com/XtLx1I5.png',''),
	(14,'Brann Stark','Stark',3,'https://i.imgur.com/TTy0VC9.png','https://vignette.wikia.nocookie.net/gameofthrones/images/8/8a/House-Stark-Main-Shield.PNG/revision/latest?cb=20170101103142'),
	(15,'Rickon Stark','Stark',4,'https://i.imgur.com/YpUsthE.png','https://vignette.wikia.nocookie.net/gameofthrones/images/8/8a/House-Stark-Main-Shield.PNG/revision/latest?cb=20170101103142'),
	(16,'Aemon Targaryen','Targaryen',4,'https://i.imgur.com/FMAb5gW.png','https://vignette.wikia.nocookie.net/gameofthrones/images/4/43/House-Targaryen-Main-Shield.PNG/revision/latest?cb=20170510235320'),
	(18,'Jon Snow','Targaryen',1,'https://i.imgur.com/7MXSZ6b.png','https://vignette.wikia.nocookie.net/gameofthrones/images/d/d4/Jon_Snow_family_tree_image.jpg/revision/latest/scale-to-width-down/100?cb=20160616211642'),
	(19,'Viserys Targaryen','Targaryen',4,'https://i.imgur.com/PYW8kBa.png','https://vignette.wikia.nocookie.net/gameofthrones/images/4/43/House-Targaryen-Main-Shield.PNG/revision/latest?cb=20170510235320'),
	(20,'Daenerys Targaryen','Targaryen',2,'https://i.imgur.com/ZUy2dm2.png','https://vignette.wikia.nocookie.net/gameofthrones/images/4/43/House-Targaryen-Main-Shield.PNG/revision/latest?cb=20170510235320'),
	(21,'Joffrey Baratheon','Lannister',2,'https://i.imgur.com/er8yt9V.png','https://vignette.wikia.nocookie.net/gameofthrones/images/8/8a/House-Lannister-Main-Shield.PNG/revision/latest?cb=20170101095357'),
	(23,'Myrcella Baratheon','Lannister',1,'https://i.imgur.com/c1MR3ag.png','https://i.imgur.com/lgIk8mF.png'),
	(24,'Tommen Baratheon','Lannister',2,'https://i.imgur.com/Vuphd98.png','https://i.imgur.com/lgIk8mF.png'),
	(27,'Tyrion Lannister','Lannister',4,'https://i.imgur.com/iQVSovg.png','https://i.imgur.com/lgIk8mF.png'),
	(28,'Robert Baratheon','Tyrell',1,'https://i.imgur.com/AtmikGh.png','https://vignette.wikia.nocookie.net/gameofthrones/images/0/00/House-Baratheon-Main-Shield.PNG/revision/latest?cb=20170519002924'),
	(29,'Renly Baratheon','Tyrell',2,'https://i.imgur.com/kYDxFzl.png','https://vignette.wikia.nocookie.net/gameofthrones/images/3/3d/House-Tyrell-heraldry.jpg/revision/latest/scale-to-width-down/100?cb=20140402122823'),
	(30,'Olenna Trrell','Tyrell',3,'https://i.imgur.com/2Xg0L54.png','https://vignette.wikia.nocookie.net/gameofthrones/images/3/3d/House-Tyrell-heraldry.jpg/revision/latest/scale-to-width-down/100?cb=20140402122823'),
	(31,'Samwell Tully','Tyrell',3,'https://i.imgur.com/hKh8Zg3.png','https://vignette.wikia.nocookie.net/gameofthrones/images/2/2d/House-Tarly-Main-Shield.PNG/revision/latest?cb=20170809082143'),
	(35,'Petyr Baelish','Other',2,'https://i.imgur.com/iXzAPn2.png',''),
	(36,'Stannis Baratheon','Tyrell',3,'https://i.imgur.com/wd7BYpn.png',''),
	(37,'Ramsay Bolton','Other',2,'https://i.imgur.com/8hL0DKe.png',''),
	(38,'Roose Bolton','Other',2,'https://i.imgur.com/VA4ILVj.png',''),
	(39,'Brienne of Tarth','Other',4,'https://i.imgur.com/7bilc7m.png',''),
	(40,'Bronn','Other',3,'https://i.imgur.com/kLDMQnT.png',''),
	(41,'Gregor Clegane','Tyrell',1,'https://i.imgur.com/Cs3bsWf.png',''),
	(42,'Sandor Clegane','Tyrell',4,'https://i.imgur.com/O5dN5y5.png',''),
	(44,'Balon Greyjoy','Tyrell',2,'https://i.imgur.com/xTJRjKg.png',''),
	(47,'Yara Greyjoy','Tyrell',2,'https://i.imgur.com/vuakgri.png',''),
	(48,'Grey Worm','Other',3,'https://i.imgur.com/WERMTzg.png',''),
	(49,'Gendry','Tyrell',1,'https://i.imgur.com/j7kGmCI.png',''),
	(50,'Gilly','Other',2,'https://i.imgur.com/qOwcUT2.png',''),
	(51,'Tormund Giantsbane','Other',3,'https://i.imgur.com/wNisIsn.png',''),
	(52,'Jaqen H’ghar','Other',1,'https://i.imgur.com/5xKOUSu.png',''),
	(53,'High Sparrow','Other',1,'https://i.imgur.com/Zojzqhr.png',''),
	(54,'Hodor','Other',1,'https://i.imgur.com/yltBBR0.png',''),
	(55,'Hot Pie','Other',1,'https://i.imgur.com/SWTuopp.png',''),
	(56,'Oberyn Martell','Other',1,'https://i.imgur.com/IeYPHhd.png',''),
	(57,'Melisandre','Other',1,'https://i.imgur.com/9pVeUQ1.png',''),
	(58,'Jorah Mormont','Other',1,'https://i.imgur.com/UqRoAwg.png',''),
	(59,'Qyburn','Other',1,'https://i.imgur.com/0JPFuTP.png',''),
	(60,'Meera Reed','Other',1,'https://i.imgur.com/ASoZwAV.png',''),
	(61,'Ellaria Sand','Martel',1,'https://i.imgur.com/swLzL8C.png',''),
	(62,'Davos Seaworth','Other',4,'https://i.imgur.com/xuzk9Ye.png',''),
	(63,'Shae','Other',1,'https://i.imgur.com/Kwldvfl.png',''),
	(64,'Bran Stark','Stark',1,'https://i.imgur.com/TTy0VC9.png',''),
	(65,'Catelyn Stark','Tyrell',1,'https://i.imgur.com/ty3KHmE.png',''),
	(67,'Varys','Other',4,'https://i.imgur.com/LKktyuS.png',''),
	(68,'Ygritte','Other',1,'https://i.imgur.com/7HLn82l.png',''),
	(70,'Jojen Reed','Other',1,'https://i.imgur.com/zz98BzQ.png',''),
	(71,'Olly','Other',1,'https://i.imgur.com/12YYR7B.png',''),
	(74,'Daario Naharis','Other',1,'https://i.imgur.com/0BRg4Ht.png',''),
	(75,'Shireen Baratheon','Other',1,'https://i.imgur.com/lGzCRF2.png',''),
	(77,'Missandei','Other',1,'https://i.imgur.com/BPkCQSW.png',''),
	(80,'Ros','Other',1,'https://i.imgur.com/oJxURKr.png',''),
	(81,'Mance Rayder','Other',1,'https://i.imgur.com/B7fCtO5.png',''),
	(83,'Maester Luwin','Other',1,'https://i.imgur.com/EBUwXt7.png',''),
	(84,'Loras Tyrell','Tyrell',1,'https://i.imgur.com/sU1puZJ.png',''),
	(86,'Jeor Mormont','Other',1,'https://i.imgur.com/iXr6Uc9.png',''),
	(88,'Osha','Other',1,'https://i.imgur.com/SyLpMzO.png',''),
	(89,'Syrio Forel','Other',1,'https://i.imgur.com/4Eabo7o.png',''),
	(90,'The Night King','Other',1,'https://i.imgur.com/VN9ZG11.png',''),
	(91,'Oberon','Other',1,'https://i.imgur.com/IeYPHhd.png',''),
	(94,'Reek','Tyrell',1,'https://i.imgur.com/TCaIPKU.png',''),
	(96,'Rob Stark','Stark',1,'https://i.imgur.com/gYwdGFW.png',''),
	(97,'Obara Sand','Tyrell',1,'https://i.imgur.com/wttczPe.png','https://vignette.wikia.nocookie.net/gameofthrones/images/2/2f/House-Martell-heraldry.jpg/revision/latest/scale-to-width-down/100?cb=20140407045115'),
	(98,'Nymeria Sand','Tyrell',1,'https://i.imgur.com/neg2sHL.png',''),
	(99,'Tyene Sand','Tyrell',1,'https://i.imgur.com/jGnKARd.png',''),
	(100,'Ned Stark','Stark',3,'https://i.imgur.com/LYBypB7.png','https://vignette.wikia.nocookie.net/gameofthrones/images/8/8a/House-Stark-Main-Shield.PNG/revision/latest?cb=20170101103142'),
	(101,'Benjen Stark','Stark',4,'https://i.imgur.com/oxiCQKu.png','https://vignette.wikia.nocookie.net/gameofthrones/images/8/8a/House-Stark-Main-Shield.PNG/revision/latest?cb=20170101103142'),
	(102,'Doran Martell','Tyrell',1,'https://i.imgur.com/nF8pcOx.png','');